# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-03-01 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20160301_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
